# Generated by Django 5.0.4 on 2024-04-22 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='waiter',
            name='employee_number',
            field=models.CharField(default='DEFAULT_EMPLOYEE_NUMBER', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='waiter',
            name='phone_number',
            field=models.CharField(default='DEFAULT_PHONE_NUMBER', max_length=15),
        ),
    ]
