# Generated by Django 5.0.4 on 2024-04-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manager',
            managers=[
            ],
        ),
    ]
