# Generated by Django 5.0.4 on 2024-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_manager_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='employee_number',
            field=models.CharField(default='00000000', max_length=20, unique=True),
        ),
    ]
