# Generated by Django 5.0.4 on 2024-04-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_manager_groups_alter_manager_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
